"""empty message

Revision ID: 51c2c10434fd
Revises: 
Create Date: 2023-03-12 00:16:35.027488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c2c10434fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Properties', 
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('num_bed', sa.Integer(), nullable=True),
    sa.Column('num_bath', sa.Numeric(), nullable=True),
    sa.Column('prop_location', sa.String(length=80), nullable=True),
    sa.Column('price', sa.String(length=128), nullable=True),
    sa.Column('prop_type', sa.String(length=20), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Properties')
    # ### end Alembic commands ###
