"""empty message
Revision ID: 7b038c23d9ce
Revises: 51c2c10434fd
Create Date: 2023-03-09 02:22:04.443709
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b038c23d9ce'
down_revision = '51c2c10434fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Properties', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###